import { FullScreenLayout, ScreenConfiguration, ScreenConfigurationCSS, WidgetLayoutConfiguration } from "src/app/generated-protos/screen-configuration";

export type WidgetReference = {
  widget: WidgetLayoutConfiguration;
  name: string;
  type: string;
  page: number;
};

export type ScreenTemplate = {
  id: string;
  templateIcon: string;
  templateName: string;
  layout: FullScreenLayout;
  screenConfiguration: ScreenConfigurationCSS;
};

export const DEFAULT_SCREEN_CONFIGURATION: ScreenConfiguration = {
  id: "",
  snapshotParentId: "",
  reviewerId: "",
  reviewerExpirationDateUnixSec: 0,
  name: "",
  description: "",
  tags: [],
  modifiedUnixSec: 0,
  owner: undefined,
  scanConfigurations: {},
  browseTabHidden: false,
  codeEditorTabHidden: false,
  elementMapsTabHidden: false,
  layouts: [
    {
      tabId: "",
      tabName: "",
      tabDescription: "Standard Layout",
      hidden: false,
      tags: [],
      rows: [{ height: 3 }, { height: 2 }],
      columns: [{ width: 3 }, { width: 2 }, { width: 2 }, { width: 2 }],
      widgets: [
        {
          id: "",
          type: "context-image",
          startRow: 1,
          startColumn: 1,
          endRow: 2,
          endColumn: 2,
          data: undefined,
        },
        {
          id: "",
          type: "spectrum-chart",
          startRow: 1,
          startColumn: 2,
          endRow: 2,
          endColumn: 5,
          data: undefined,
        },
        {
          id: "",
          type: "histogram",
          startRow: 2,
          startColumn: 1,
          endRow: 3,
          endColumn: 2,
          data: undefined,
        },
        {
          id: "",
          type: "chord-diagram",
          startRow: 2,
          startColumn: 2,
          endRow: 3,
          endColumn: 3,
          data: undefined,
        },
        {
          id: "",
          type: "ternary-plot",
          startRow: 2,
          startColumn: 3,
          endRow: 3,
          endColumn: 4,
          data: undefined,
        },
        {
          id: "",
          type: "binary-plot",
          startRow: 2,
          startColumn: 4,
          endRow: 3,
          endColumn: 5,
          data: undefined,
        },
      ],
    },
  ],
};

export const createDefaultScreenConfiguration = (): ScreenConfiguration => {
  return JSON.parse(JSON.stringify(DEFAULT_SCREEN_CONFIGURATION));
};

const ANALYSIS_STANDARD_LAYOUT = createDefaultScreenConfiguration().layouts[0];
const ANALYSIS_LAYOUT_2: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "Layout 2",
  hidden: false,
  tags: [],
  rows: [{ height: 2 }, { height: 2 }],
  columns: [{ width: 2 }, { width: 2 }, { width: 2 }, { width: 2 }, { width: 2 }, { width: 2 }],
  widgets: [
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 1,
      endRow: 3,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "binary-plot",
      startRow: 1,
      startColumn: 4,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "binary-plot",
      startRow: 1,
      startColumn: 5,
      endRow: 2,
      endColumn: 5,
      data: undefined,
    },
    {
      id: "",
      type: "binary-plot",
      startRow: 1,
      startColumn: 6,
      endRow: 2,
      endColumn: 6,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 2,
      startColumn: 4,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 2,
      startColumn: 5,
      endRow: 2,
      endColumn: 5,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 2,
      startColumn: 6,
      endRow: 2,
      endColumn: 6,
      data: undefined,
    },
  ],
};

const ANALYSIS_LAYOUT_3: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "Layout 3",
  hidden: false,
  tags: [],
  rows: [{ height: 1 }],
  columns: [{ width: 1 }, { width: 1 }],
  widgets: [
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 1,
      endRow: 1,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 2,
      endRow: 2,
      endColumn: 2,
      data: undefined,
    },
  ],
};

const ANALYSIS_LAYOUT_4: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "Layout 4",
  hidden: false,
  tags: [],
  rows: [{ height: 1 }, { height: 1 }],
  columns: [{ width: 1 }, { width: 1 }, { width: 1 }, { width: 1 }],
  widgets: [
    {
      id: "",
      type: "binary-plot",
      startRow: 1,
      startColumn: 1,
      endRow: 2,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 1,
      startColumn: 2,
      endRow: 2,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "binary-plot",
      startRow: 1,
      startColumn: 3,
      endRow: 2,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 1,
      startColumn: 4,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "binary-plot",
      startRow: 2,
      startColumn: 1,
      endRow: 3,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 2,
      startColumn: 2,
      endRow: 3,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "binary-plot",
      startRow: 2,
      startColumn: 3,
      endRow: 3,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "ternary-plot",
      startRow: 2,
      startColumn: 4,
      endRow: 3,
      endColumn: 4,
      data: undefined,
    },
  ],
};

const ALL_CONTEXT_IMAGES: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "2x4 Context Images",
  hidden: false,
  tags: [],
  rows: [{ height: 1 }, { height: 1 }],
  columns: [{ width: 1 }, { width: 1 }, { width: 1 }, { width: 1 }],
  widgets: [
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 1,
      endRow: 2,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 2,
      endRow: 2,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 3,
      endRow: 2,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 4,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 2,
      startColumn: 1,
      endRow: 3,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 2,
      startColumn: 2,
      endRow: 3,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 2,
      startColumn: 3,
      endRow: 3,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 2,
      startColumn: 4,
      endRow: 3,
      endColumn: 4,
      data: undefined,
    },
  ],
};

const CONTEXT_IMAGE_PCP: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "2x4 Context Images",
  hidden: false,
  tags: [],
  rows: [{ height: 1 }, { height: 1 }],
  columns: [{ width: 1 }, { width: 1 }, { width: 1 }, { width: 1 }],
  widgets: [
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 1,
      endRow: 2,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 2,
      endRow: 2,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 3,
      endRow: 2,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "context-image",
      startRow: 1,
      startColumn: 4,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "parallel-coordinates-plot",
      startRow: 2,
      startColumn: 1,
      endRow: 3,
      endColumn: 1,
      data: undefined,
    },
    {
      id: "",
      type: "parallel-coordinates-plot",
      startRow: 2,
      startColumn: 2,
      endRow: 3,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "parallel-coordinates-plot",
      startRow: 2,
      startColumn: 3,
      endRow: 3,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "parallel-coordinates-plot",
      startRow: 2,
      startColumn: 4,
      endRow: 3,
      endColumn: 4,
      data: undefined,
    },
  ],
};

export const generateTemplateConfiguration = (layout: FullScreenLayout): ScreenConfigurationCSS => {
  const templateRows = layout.rows.map(row => `${row.height}fr`).join(" ");
  const templateColumns = layout.columns.map(column => `${column.width}fr`).join(" ");
  return { templateColumns, templateRows };
};

export const ANALYSIS_TEMPLATES: ScreenTemplate[] = [
  {
    id: "standard-layout",
    templateName: "Standard Layout",
    templateIcon: "assets/icons/workspaces-tab.svg",
    layout: ANALYSIS_STANDARD_LAYOUT,
    screenConfiguration: generateTemplateConfiguration(ANALYSIS_STANDARD_LAYOUT),
  },
  {
    id: "layout-2",
    templateName: "Layout 2",
    templateIcon: "assets/icons/workspaces-tab.svg",
    layout: ANALYSIS_LAYOUT_2,
    screenConfiguration: generateTemplateConfiguration(ANALYSIS_LAYOUT_2),
  },
  {
    id: "layout-3",
    templateName: "Layout 3",
    templateIcon: "assets/icons/workspaces-tab.svg",
    layout: ANALYSIS_LAYOUT_3,
    screenConfiguration: generateTemplateConfiguration(ANALYSIS_LAYOUT_3),
  },
  {
    id: "layout-4",
    templateName: "Layout 4",
    templateIcon: "assets/icons/workspaces-tab.svg",
    layout: ANALYSIS_LAYOUT_4,
    screenConfiguration: generateTemplateConfiguration(ANALYSIS_LAYOUT_4),
  },
  {
    id: "all-context-images",
    templateName: "2x4 Context Images",
    templateIcon: "assets/icons/workspaces-tab.svg",
    layout: ALL_CONTEXT_IMAGES,
    screenConfiguration: generateTemplateConfiguration(ALL_CONTEXT_IMAGES),
  },
  {
    id: "all-context-images",
    templateName: "2x4 Context Images/PCP",
    templateIcon: "assets/icons/workspaces-tab.svg",
    layout: CONTEXT_IMAGE_PCP,
    screenConfiguration: generateTemplateConfiguration(CONTEXT_IMAGE_PCP),
  },
];

export const createDefaultAnalysisTemplates = (): ScreenTemplate[] => {
  return JSON.parse(JSON.stringify(ANALYSIS_TEMPLATES));
};

export const BROWSE_TEMPLATE: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "",
  hidden: false,
  tags: [],
  rows: [{ height: 2 }, { height: 3 }, { height: 3 }, { height: 3 }, { height: 3 }],
  columns: [{ width: 1 }, { width: 1 }, { width: 1 }, { width: 1 }, { width: 2 }],
  widgets: [
    // Header bar
    {
      id: "",
      type: "",
      startRow: 1,
      startColumn: 1,
      endRow: 1,
      endColumn: 6,
      data: undefined,
    },
    // Scan items
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 1,
      endRow: 2,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 2,
      endRow: 2,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 3,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 4,
      endRow: 2,
      endColumn: 5,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 3,
      startColumn: 1,
      endRow: 3,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 3,
      startColumn: 2,
      endRow: 3,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 3,
      startColumn: 3,
      endRow: 3,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 3,
      startColumn: 4,
      endRow: 3,
      endColumn: 5,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 4,
      startColumn: 1,
      endRow: 4,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 4,
      startColumn: 2,
      endRow: 4,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 4,
      startColumn: 3,
      endRow: 4,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 4,
      startColumn: 4,
      endRow: 4,
      endColumn: 5,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 5,
      startColumn: 1,
      endRow: 5,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 5,
      startColumn: 2,
      endRow: 5,
      endColumn: 3,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 5,
      startColumn: 3,
      endRow: 5,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 5,
      startColumn: 4,
      endRow: 5,
      endColumn: 5,
      data: undefined,
    },

    // Browse sidepanel
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 5,
      endRow: 6,
      endColumn: 5,
      data: undefined,
    },
  ],
};

export const CODE_EDITOR_TEMPLATE: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "",
  hidden: false,
  tags: [],
  rows: [{ height: 3 }],
  columns: [{ width: 3 }, { width: 1 }],
  widgets: [
    {
      id: "",
      type: "",
      startRow: 1,
      startColumn: 1,
      endRow: 1,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 1,
      startColumn: 2,
      endRow: 1,
      endColumn: 2,
      data: undefined,
    },
  ],
};

export const ELEMENT_MAPS_TEMPLATE: FullScreenLayout = {
  tabId: "",
  tabName: "",
  tabDescription: "",
  hidden: false,
  tags: [],
  rows: [{ height: 2 }, { height: 2 }],
  columns: [{ width: 2 }, { width: 2 }],
  widgets: [
    {
      id: "",
      type: "",
      startRow: 1,
      startColumn: 1,
      endRow: 1,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 1,
      startColumn: 2,
      endRow: 1,
      endColumn: 4,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 1,
      endRow: 2,
      endColumn: 2,
      data: undefined,
    },
    {
      id: "",
      type: "",
      startRow: 2,
      startColumn: 2,
      endRow: 2,
      endColumn: 4,
      data: undefined,
    },
  ],
};

export const OTHER_TEMPLATES: ScreenTemplate[] = [
  {
    id: "browse",
    templateName: "Browse",
    templateIcon: "assets/tab-icons/browse.svg",
    layout: BROWSE_TEMPLATE,
    screenConfiguration: generateTemplateConfiguration(BROWSE_TEMPLATE),
  },
  {
    id: "code-editor",
    templateName: "Code Editor",
    templateIcon: "assets/tab-icons/code-editor.svg",
    layout: CODE_EDITOR_TEMPLATE,
    screenConfiguration: generateTemplateConfiguration(CODE_EDITOR_TEMPLATE),
  },
  {
    id: "element-maps",
    templateName: "Element Maps",
    templateIcon: "assets/tab-icons/element-maps.svg",
    layout: ELEMENT_MAPS_TEMPLATE,
    screenConfiguration: generateTemplateConfiguration(ELEMENT_MAPS_TEMPLATE),
  },
];

export const createDefaultOtherTemplates = (): ScreenTemplate[] => {
  return JSON.parse(JSON.stringify(OTHER_TEMPLATES));
};
