name: UI Build & Test (Release)

on:
  push:
    tags:
      - '*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    uses: ./.github/workflows/main.yml
    with:
      version_format: '${major}.${minor}.${patch}'
    secrets: inherit
