name: UI Build & Test (Main branch)

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  slug:
    runs-on: ubuntu-latest
    outputs:
      github_ref_slug: ${{ env.GITHUB_REF_NAME_SLUG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@v4.4.0
  staging:
    uses: ./.github/workflows/main.yml
    needs: slug
    with:
      version_format: '${major}.${minor}.${patch}-RC${increment}'
    secrets: inherit
